# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('events.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='live',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
